name: NodeJS CI

on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: set uo and Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies, build and test
        run: |
          echo "Building backend..."
          cd ./backend
          npm install
          npm run build --if-present
          npm test
          cd ../frontend
          cd ./busca-pet
          npm install
          npm run build
