name: NodeJS CI

on:
  push: 
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: set uo and Use Node.js ${{ matrix.node-version }} #
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies, build and test #
        run: |
          cd ./backend
          echo "STARTING INTALL IN BACKEND"
          npm install
          echo "INSTALL DONE"
          echo "STARTING TEST IN BACKEND"
          npm test -- --forceExit
          echo "TEST DONE"
          cd ../frontend/busca-pet
          echo "STARTING INSTALL IN FRONTEND"
          npm install
          echo "INSTALL DONE"
          echo "STARTING BUILD IN FRONTEND"
          npm run build
          echo "BUILD DONE"
